services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - backend-node-modules:/usr/src/app/node_modules
    environment:
      APP_PORT: 3000
      DATABASE_TYPE: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: dbpostgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: pass
      JWT_SECRET: X8vT9Lm2zP4Qr7YkJH5oNCDwGbV1As0XFKMBZYpW3EI6RJmsQo
      JWT_ALG: HS256
      JWT_EXP: 1d
      SECRET_SALT: M5aQ8X7zN1vT4L2pJH9oYkDCGBV0FsKWBZYR3EI6RJmsQoH57
      SALT_ROUNDS: 10
    networks:
      - system
      
 
  scripts:
    build:
      context: ./scripts
    container_name: script-mongo
    ports:
      - "8000:8000"
    networks:
      - system

      
volumes:
  backend-node-modules:
  
networks:
  system:
    external: true